site_name: Angelo De Castro
site_url: https://angelodecastr.github.io/My-Portfolio/

theme:
  name: material

  palette:
    - media: "(prefers-color-scheme)"
      toggle:
        icon: material/link
        name: Switch to light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: black
      accent: indigo
      toggle:
        icon: material/toggle-switch-off
        name: Switch to system preference

  font:
    text: Roboto
    code: Roboto Mono

  icon:
    logo: logo

  features:
    - content.code.annotate
    - content.code.copy
    - content.tabs.link
    - announce.dismiss
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.expand
    - navigation.top
    - navigation.footer
    - navigation.tracking
    - search.highlight
    - search.share
    - search.suggest
    - navigation.instant
    - navigation.instant.prefetch
    - navigation.instant.progress
    - navigation.instant.preview
    - toc.integrate
    - toc.follow

markdown_extensions:
  - codehilite
  - admonition
  - toc:
      permalink: true
      toc_depth: 3
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys


nav:
  - Home: index.md
  - Work Experience: Work Experience.md
  - Skills: Skills.md

  - Projects: 
      - Guacamole: Projects/Guacamole.md
      - Ansible Automation: Projects/Ansible.md
      - OpManager: Projects/OpMan.md
      - POS Remotely: Projects/Remotely.md
      - Uptime Kuma: Projects/Uptime.md
      - Active Directory: Projects/ActiveDirectory.md
      - NocoDB: Projects/NocoDB.md
  

  - Certifications:
        - Fortinet: Certifications/Fortinet.md
        - Cisco: Certifications/Introduction.md
        - Computer Systems Servicing NC2: Certifications/NC2.md
  

extra:
  social:
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/angelo-decastro/
      name: Angelo L. De Castro
  
